//--------------------------------------------------
// Enumerations of User Timer Events
//--------------------------------------------------
    _USER_TIMER_EVENT_KEY_REPEAT_ENABLE,
    _USER_TIMER_EVENT_KEY_SCAN_READY,
    _USER_TIMER_EVENT_OSD_DISABLE_OSD_LOGO,
    _USER_TIMER_EVENT_OSD_SHOW_NO_CABLE,
    _USER_TIMER_EVENT_OSD_SHOW_NO_SIGNAL,
    _USER_TIMER_EVENT_OSD_SHOW_POWER_SAVING,
    _USER_TIMER_EVENT_GO_TO_POWER_SAVING,
    _USER_TIMER_EVENT_OSD_DISABLE,
    _USER_TIMER_EVENT_PANEL_BACKLIGHT_ON,
    _USER_TIMER_EVENT_PANEL_POWER_OFF,
    _USER_TIMER_EVENT_DO_AUTO_COLOR,
    _USER_TIMER_EVENT_PANEL_USED_TIMER,

#if(_HIGHLIGHT_WINDOW_SUPPORT == _ON)
    _USER_TIMER_EVENT_HLWIN_TYPE5_MOVE,
#endif

    _USER_TIMER_EVENT_OSD_KEYINFO_UNHIGHLIGHT,
    _USER_TIMER_EVENT_OSD_SHOW_DP_VERSION_SELECT,

#if(_HDMI_CEC_SUPPORT == _ON)
    _USER_TIMER_EVENT_CEC_LA_POLLING,
#endif

#if(_FREESYNC_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_SHOW_FREESYNC_VFREQ,
#endif

#if(_FREEZE_SUPPORT == _ON)
    _USER_TIMER_EVENT_OSD_DISABLE_FREEZE_MSG,
#endif
#if(_AUDIO_SUPPORT == _ON)
#if(_AUDIO_TTS_SUPPORT_TYPE == _AUDIO_TTS_EMBEDDED_TYPE)
    _USER_TIMER_EVENT_AUDIO_TTS_SHOW_LOGO,
    _USER_TIMER_EVENT_AUDIO_TTS_POWER_OFF,
#endif
#endif
#if(_LD_HDR10_BOOST_SUPPORT == _ON)
     _USER_TIMER_EVENT_HDR_BOOST,
     _USER_TIMER_EVENT_HDR_COOL,
#endif

	_USER_TIMER_EVENT_LED_MODE_FLICKER,
	_USER_TIMER_EVENT_AUTO_POWER_DOWN,
	_USER_TIMER_EVENT_BUININ_MSG,
#if(_DCR_SUPPORT == _ON)
	 _USER_TIMER_EVENT_DCR_CAL_TIME,
	 _USER_TIMER_EVENT_DCR_TUNE_PWM_TIMER,
	
#endif
	_USER_TIMER_EVENT_DO_POWER_DOWN,
	_USER_TIMER_EVENT_MPRT,
    _USER_TIMER_EVENT_DO_EXIT,
 	 _USER_TIMER_EVENT_IR_PROC,
 	 
#if 1//(_DEF_HOTKEY_LONG)
	_USER_TIMER_EVENT_RIGHT_LONG,
	_USER_TIMER_EVENT_LEFT_LONG,
#endif
#if 1//(_DEF_MENU_LOCK)
    _USER_TIMER_EVENT_MENU_LOCK,
#endif
    //_USER_TIMER_EVENT_RIGHT_KEY,
   // _USER_TIMER_EVENT_LEFT_KEY,
	_USER_TIMER_EVENT_RG_LED_FLICKER,
	_USER_TIMER_EVENT_SAVE_NVRAM_OSDUSERDATA,

#if _DEF_GuangGan_FUN
	_USER_TIMER_EVENT_GuangGan_Back,
#endif
